server:
  port: 8001

spring:
  profiles:
    active: dev
  application:
    name: cloud-oa-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://106.14.176.167:3306/htwy_oa?useUnicode=true&characterEncoding=utf8 # 数据库名称
    username: root
    password: 123456
  jpa:
    show_sql: true

  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    settings:
      number_format: 0.##

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace

mybatis:
  mapper-locations: classpath*:/mappers/**/*.xml
#file:
#  root:
#    path: /Users/xuweiwei/code/gitcode/oa_core/oa-core/src/main/resources/static/file
#img:
#  rootpath: /Users/xuweiwei/code/gitcode/oa_core/oa-core/src/main/resources/static/images
#attachment:
#  roopath: /Users/xuweiwei/code/gitcode/oa_core/oa-core/src/main/resources/static/attachment
file:
  root:
    path: F:\code\oa\oa-core\src\main\resources\static\file
img:
  rootpath: F:\code\oa\oa-core\src\main\resources\static\images
attachment:
  roopath: F:\code\oa\oa-core\src\main\resources\static\attachment